### ISSUE TITLE
No need to wait after Wire.requestFrom().

### ISSUE THREAD

**Issue by Koepel** [Seeed-Studio/Multi_Channel_Relay_Arduino_Library#1]
In the file "multi_channel_relay.cpp", this line "`while(!Wire.available());`" after the Wire.requestFrom() can be removed.
Explanation: [Common-mistakes#1](https://github.com/Koepel/How-to-use-the-Arduino-Wire-library/wiki/Common-mistakes#1)

**Comment by KillingJacky** [comment]
Thank you for pointing out the mistake. Get it fixed.
