### ISSUE TITLE
reading relay state from stm32

### ISSUE THREAD

**Issue by chrisovergaauw** [Seeed-Studio/Multi_Channel_Relay_Arduino_Library#3]
Hi,

Can the channel state also be read from the chip rather then the in-memory copy you're keeping here?

https://github.com/Seeed-Studio/Multi_Channel_Relay_Arduino_Library/blob/b7e592874e468fa57538fdde86874de4c0f9cd5e/multi_channel_relay.cpp#L58

**Comment by HeneryH** [comment]
Chris, have you determined if the state can be read?

**Comment by chrisovergaauw** [comment]
Sorry, I haven't been been able to to figure this out and moved on under the assumption that it cannot be done.
