### ISSUE TITLE
Multiple boards

### ISSUE THREAD

**Issue by lelez1000** [Seeed-Studio/Multi_Channel_Relay_Arduino_Library#4]
Hi,

in case I have more than one board connected to the arduino, how could I manage both of them?

**Comment by Lesords** [comment]
Hello,

I'm very sorry to have kept you waiting so long.

Do you mean downloading programs to different boards at the same time?

If so, you can open a new Arduino and select a different serial port number to download programs to the specified board.

**Comment by Lesords** [comment]
Hello,

I\'m going to close this issue, feel free to re-open it if you have any other questions.

[Autocommentary]
