### ISSUE TITLE
No choice of Wire we want to use

### ISSUE THREAD

**Issue by fo8x** [Seeed-Studio/Multi_Channel_Relay_Arduino_Library#5]
In the library, we don't have the choice of the Wire we want to use (Wire, Wire1, etc)

**Comment by Lesords** [comment]
Hello,

I'm very sorry to have kept you waiting so long.

Currently this library does not support selecting a specific wire.

Do you still need this feature now?

**Comment by Lesords** [comment]
Hello,

I\'m going to close this issue, feel free to re-open it if you have any other questions.

[Autocommentary]
